const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(Number(n||0));
let products=[],settings={},cart=JSON.parse(localStorage.getItem("monowear-cart")||"[]");
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
async function loadStore(){try{const r=await fetch("/api/store"),d=await r.json();settings=d.settings||{};products=d.products||[];$("brandName").childNodes[0].textContent=settings.brand_name||"MONOWEAR";document.title=(settings.brand_name||"MONOWEAR")+" — Live the Name";$("announcement").textContent=settings.announcement||"";$("heroTitle").innerHTML=esc(settings.hero_title||"HELP IS ON THE WAY").replace(/ ON THE WAY/i,"<br><span>ON THE WAY.</span>");$("heroSubtitle").textContent=settings.hero_subtitle||"";$("heroCta").innerHTML=esc(settings.hero_cta||"SHOP THE DROP")+" ↗";$("footerTagline").textContent=settings.tagline||"";if(settings.instagram){$("instagramLink").href=settings.instagram;$("newsletterLink").href=settings.instagram}else $("instagramLink").hidden=true;if(settings.contact_email)$("emailLink").href="mailto:"+settings.contact_email;else $("emailLink").hidden=true;const cats=[...new Set(products.map(p=>p.category).filter(Boolean))];$("categoryFilter").innerHTML='<option value="">All pieces</option>'+cats.map(c=>`<option>${esc(c)}</option>`).join("");renderProducts();}catch{$("productGrid").innerHTML='<p class="muted">The collection could not load. Please refresh.</p>'}renderCart();$("year").textContent=new Date().getFullYear();}
function renderProducts(){const q=$("searchProducts").value.toLowerCase(),cat=$("categoryFilter").value;const list=products.filter(p=>(!cat||p.category===cat)&&(`${p.name} ${p.category} ${p.description}`.toLowerCase().includes(q)));if(!list.length){$("productGrid").innerHTML='<p class="empty-state">No pieces match that search.</p>';return}$("productGrid").innerHTML=list.map(p=>`<article class="product-card"><div class="product-image">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy">`:`<div class="image-placeholder">MONO<br>— ${esc(p.category).toUpperCase()} —</div>`}${p.featured?'<span class="product-badge">FEATURED</span>':""}${p.stock<=0?'<span class="sold-badge">SOLD OUT</span>':""}</div><div class="product-meta"><h3>${esc(p.name)}</h3><span class="price">${money(p.price)}</span></div><div class="product-category">${esc(p.category)} · ${p.stock} available</div><p class="product-description">${esc(p.description)}</p><div class="product-actions"><select class="size-select" id="size-${p.id}" aria-label="Choose size">${p.sizes.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join("")}</select><button class="add-button" ${p.stock<=0?"disabled":""} onclick="addToCart(${p.id})">${p.stock<=0?"SOLD OUT":"ADD TO BAG +"}</button></div></article>`).join("");}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p)return;const size=$("size-"+id).value,found=cart.find(x=>x.id===id&&x.size===size);if(found){if(found.qty>=p.stock)return alert("That is all the available stock.");found.qty++;}else cart.push({id:p.id,name:p.name,price:p.price,size,qty:1});saveCart();openCart();}
function saveCart(){localStorage.setItem("monowear-cart",JSON.stringify(cart));renderCart();}
function renderCart(){const count=cart.reduce((a,x)=>a+x.qty,0),total=cart.reduce((a,x)=>a+x.price*x.qty,0);$("cartCount").textContent=count;$("drawerCount").textContent="("+count+")";$("cartTotal").textContent=money(total);$("checkoutTotal").textContent=money(total);$("cartItems").innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-line"><div><h3>${esc(x.name)}</h3><p>Size: ${esc(x.size)} · Qty: ${x.qty}</p><p>${money(x.price*x.qty)}</p><div class="qty-actions"><button onclick="changeQty(${i},-1)">−</button><button onclick="changeQty(${i},1)">+</button><button onclick="removeCart(${i})">REMOVE</button></div></div></div>`).join(""):'<p class="muted">Your bag is empty.</p>';$("checkoutButton").disabled=!cart.length;$("checkoutButton").style.opacity=cart.length?1:.5;}
function changeQty(i,d){const p=products.find(x=>x.id===cart[i].id);if(!p)return;if(d>0&&cart[i].qty>=p.stock)return alert("Stock limit reached.");cart[i].qty+=d;if(cart[i].qty<=0)cart.splice(i,1);saveCart();}
function removeCart(i){cart.splice(i,1);saveCart();}
function openCart(){$("cartDrawer").classList.add("open");$("cartOverlay").classList.add("open");document.body.style.overflow="hidden";}
function closeCart(){$("cartDrawer").classList.remove("open");$("cartOverlay").classList.remove("open");document.body.style.overflow="";}
$("cartToggle").onclick=openCart;$("closeCart").onclick=closeCart;$("cartOverlay").onclick=closeCart;$("searchProducts").addEventListener("input",renderProducts);$("categoryFilter").addEventListener("change",renderProducts);
$("checkoutButton").onclick=()=>{if(!cart.length)return;$("checkoutMessage").textContent="";$("checkoutDialog").showModal();};$("closeCheckout").onclick=()=>$("checkoutDialog").close();
$("checkoutForm").addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget,body=Object.fromEntries(new FormData(f).entries());body.items=cart.map(({id,qty,size})=>({id,qty,size}));const btn=f.querySelector('button[type=submit]');btn.disabled=true;btn.textContent="CREATING ORDER…";$("checkoutMessage").textContent="";
try{const r=await fetch("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error||"Checkout failed.");if(d.authorization_url){location.href=d.authorization_url;return;}cart=[];saveCart();f.reset();$("checkoutMessage").textContent=`${d.message} Reference: ${d.reference}.`; }catch(err){$("checkoutMessage").textContent=err.message;}finally{btn.disabled=false;btn.textContent="CONTINUE TO CHECKOUT ↗";}});
loadStore();