const $=id=>document.getElementById(id);let currentProducts=[];
async function api(url,options={}){const r=await fetch(url,{credentials:"same-origin",...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Something went wrong.");return d;}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}function money(n){return new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(Number(n||0));}
function toast(m){const t=$("toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2600);}
function showApp(email){$("loginScreen").hidden=true;$("appScreen").hidden=false;$("loggedEmail").textContent=email||"";loadProducts();loadSettings();loadSummary();}
function showLogin(){$("loginScreen").hidden=false;$("appScreen").hidden=true;}
async function checkAuth(){try{const m=await api("/api/admin/me");if(m.authenticated)showApp(m.email);else showLogin();}catch{showLogin();}}
$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginError").textContent="";try{const r=await api("/api/admin/login",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});showApp(r.email);}catch(err){$("loginError").textContent=err.message;}};
$("logoutButton").onclick=async()=>{try{await api("/api/admin/logout",{method:"POST"});}finally{showLogin();}};
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
function switchTab(tab){document.querySelectorAll(".nav").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));document.querySelectorAll(".tab-panel").forEach(s=>s.hidden=s.id!=="tab-"+tab);$("pageTitle").textContent=({overview:"Overview",products:"Products",appearance:"Store editor",orders:"Orders"})[tab];if(tab==="orders")loadOrders();if(tab==="overview")loadSummary();}
async function loadSummary(){try{const d=await api("/api/admin/summary");$("statProducts").textContent=d.products;$("statOrders").textContent=d.orders;$("statPending").textContent=d.pending;$("statRevenue").textContent=money(d.revenue);}catch{}}
async function loadProducts(){try{currentProducts=await api("/api/admin/products");$("productCount").textContent=currentProducts.length;$("productsList").innerHTML=currentProducts.map(p=>`<article class="product-row"><div class="thumb">${p.image?`<img src="${esc(p.image)}" alt="">`:"MONO"}</div><div><h3>${esc(p.name)}</h3><p>${esc(p.category)} · Stock ${p.stock} · ${p.published?"Published":"Hidden"} · ${p.featured?"Featured":"Standard"}</p></div><strong class="price">${money(p.price)}</strong><div class="row-actions"><button class="small-button" onclick="editProduct(${p.id})">EDIT ↗</button></div></article>`).join("")||'<p class="muted">No products yet. Add your first product.</p>';}catch(e){toast(e.message);}}
function newProduct(){const f=$("productForm");f.reset();f.hidden=false;f.elements.id.value="";f.elements.sizes.value="S,M,L,XL";f.elements.stock.value=0;f.elements.published.checked=true;$("productFormTitle").textContent="Add a product";$("deleteProductButton").hidden=true;$("productError").textContent="";f.scrollIntoView({behavior:"smooth"});}
window.editProduct=id=>{const p=currentProducts.find(x=>x.id===id);if(!p)return;const f=$("productForm");f.reset();f.hidden=false;for(const k of ["id","name","slug","category","price","compare_price","sizes","stock","image","description"])f.elements[k].value=k==="id"?p.id:k==="sizes"?p.sizes.join(","):p[k]??"";f.elements.featured.checked=p.featured;f.elements.published.checked=p.published;$("productFormTitle").textContent="Edit product";$("deleteProductButton").hidden=false;$("productError").textContent="";f.scrollIntoView({behavior:"smooth"});};
$("newProductButton").onclick=newProduct;$("cancelProduct").onclick=()=>$("productForm").hidden=true;
$("productForm").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,id=f.elements.id.value;const body={};for(const k of ["name","slug","category","price","compare_price","sizes","stock","image","description"])body[k]=f.elements[k].value;body.price=Number(body.price);body.stock=Number(body.stock);body.compare_price=body.compare_price===""?null:Number(body.compare_price);body.sizes=body.sizes.split(",").map(s=>s.trim()).filter(Boolean);body.featured=f.elements.featured.checked;body.published=f.elements.published.checked;$("productError").textContent="";try{const file=f.elements.imageFile.files[0];if(file){const fd=new FormData();fd.append("image",file);const up=await fetch("/api/admin/uploads",{method:"POST",body:fd});const ud=await up.json();if(!up.ok)throw Error(ud.error||"Image upload failed.");body.image=ud.url;}await api(id?"/api/admin/products/"+id:"/api/admin/products",{method:id?"PUT":"POST",body:JSON.stringify(body)});f.hidden=true;await loadProducts();loadSummary();toast("Product saved. Storefront updated.");}catch(err){$("productError").textContent=err.message;}};
$("deleteProductButton").onclick=async()=>{const id=$("productForm").elements.id.value;if(!id||!confirm("Delete this product permanently?"))return;try{await api("/api/admin/products/"+id,{method:"DELETE"});$("productForm").hidden=true;await loadProducts();loadSummary();toast("Product deleted.");}catch(e){$("productError").textContent=e.message;}};
async function loadSettings(){try{const d=await api("/api/store"),f=$("settingsForm");Object.entries(d.settings||{}).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v;});}catch(e){toast(e.message);}}
$("settingsForm").onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));try{await api("/api/admin/settings",{method:"PUT",body:JSON.stringify(body)});$("settingsMessage").textContent="Saved. Your storefront changes are live.";toast("Storefront updated.");}catch(err){$("settingsMessage").textContent=err.message;}};
async function loadOrders(){try{const os=await api("/api/admin/orders");$("orderCount").textContent=os.length;$("ordersList").innerHTML=os.map(o=>`<article class="order-card"><div><h3>#${esc(o.reference||o.id)} · ${esc(o.customer_name)} · ${money(o.total)}</h3><p>${esc(o.email)} · ${esc(o.phone)}</p><p>${esc(o.address)}</p><p>${o.items.map(i=>`${esc(i.name)} / ${esc(i.size)} × ${i.qty}`).join("<br>")}</p><p>Payment: ${esc(o.payment_status)} · Received ${esc(o.created_at)}</p><p>Subtotal ${money(o.subtotal)} + delivery ${money(o.shipping)}</p>${o.events.map(v=>`<p>• ${esc(v.status)} — ${esc(v.created_at)} ${esc(v.note)}</p>`).join("")}</div><div><label class="eyebrow">FULFILMENT STATUS</label><select onchange="updateOrder(${o.id},this.value)">${["Pending payment","Paid","Processing","Shipped","Delivered","Cancelled"].map(s=>`<option ${o.status===s?"selected":""}>${s}</option>`).join("")}</select></div></article>`).join("")||'<p class="muted">No orders yet.</p>';}catch(e){toast(e.message);}}
window.updateOrder=async(id,status)=>{try{await api("/api/admin/orders/"+id,{method:"PATCH",body:JSON.stringify({status})});await loadOrders();loadSummary();toast("Order status updated.");}catch(e){toast(e.message);}};
$("refreshOrders").onclick=loadOrders;checkAuth();